// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20220128213753_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryTitle = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryTitle = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryTitle = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryTitle = "Family"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryTitle = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryTitle = "Horror"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryTitle = "Musical"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryTitle = "Mystery"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryTitle = "Romance"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryTitle = "Thriller"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryTitle = "Other"
                        });
                });

            modelBuilder.Entity("Mission4.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "The Dark Knight",
                            Year = 2008
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 4,
                            Director = "Brad Bird",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "G",
                            Title = "Ratatouille",
                            Year = 2007
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 7,
                            Director = "Michael Gracey",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "The Greatest Showman",
                            Year = 2017
                        });
                });

            modelBuilder.Entity("Mission4.Models.MovieResponse", b =>
                {
                    b.HasOne("Mission4.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
